### ISSUE TITLE
Jumping text

### ISSUE THREAD

**Issue by dronecz** [mchestr/HT1632C-Python#1]
Hi,

first of all, many thanks for your work.

I´m trying to use your code to drive 2 (maybe 4) Sure LED matrixes, but I got wierd behavior of it. 

You can see it here:

https://youtu.be/AtuNsckG1Ak

Do you have any similar experiencis like me? Have I something wrong? I wired it by your example. Text is jumping just with black background, I think. 

Many thanks for reply. 

Miroslav

**Comment by mchestr** [comment]
Hey! glad the you are finding some use for this library. To be honest I haven't touched this for almost a year, and don't currently have my LED displays at the moment, but I never experienced that issue. Do you experience this issue without the scrolling text? Make sure your wire connections are secure.

All the examples do is write a frame, display it, clear the frame and draw the next frame, so you could try experimenting with the refresh rate and see if you are having the same issue on a lower refresh rate

**Comment by dronecz** [comment]
Hi, sorry for such a late reply and thx for your answer.

You were right, I had problem with my connection, I did rookie mystake and I forget to connect ground from my RPi :-/. Anyway, I did make it work as you can see at the picture. 
![20170626_174840](https://user-images.githubusercontent.com/16454728/29556381-fc615b42-8725-11e7-958d-03a9489d113e.jpg)

I have 2 questions:
1) How can I make scrolling text quicker? I changed `time.sleep(1/30.0)` to `time.sleep(100/30.0)` and text is scrolling faster, but not fast enough, at least for me. 
2) I understand that I can change text font from library, but is there way that I can make my own font? I understand that it take HEX value of character which I want display from font.h, but I want make my own font so I can display smaileys, custom characters, etc. I mean, did you make your font or did you find it somewhere? Is there any tool which I can use to make my own font? 

Many thanks for reply and this very good library.

**Comment by mchestr** [comment]
Glad you managed to make it wor

To answer your questions:
 - to make the refresh rate faster you will want to increase the denominator in your sleep.
`time.sleep(1/30.0)` is a ~33ms refresh rate or 30 frames per second. For a 60 frames per second refresh rate you can do `time.sleep(1/60.0)` however you should experiment with that works for your displays, as you may hit a limit on the number of frames you can display per second.
- I believe I got the original from here https://github.com/DerBer/ht1632clib . You could also look around for a font generator, something like https://github.com/andykarpov/ht1632c/tree/master/dotmatrix_font_editor maybe. I haven't tested any of these sorry. To generate your own, I would need to read the C code, cause at this moment I forget how you could generate the arrays manually

**Comment by mchestr** [comment]
I have added some examples to the library on how to create your own custom fonts, feel free to check them out. If you still need help feel free to open a new issue.
