### ISSUE TITLE
Add Font ??

### ISSUE THREAD

**Issue by DizHell** [mchestr/HT1632C-Python#2]
Hello,

Thank you for this portage, it allowed me to replace my old arduino mega by a raspberry zero W.

I use your code for a Clock, but I would like to add fonts, I tried to modify font.c font.h, and interface.py, but it does not work ...

I usually program in C, and I start in python.

I hope you have 5 minutes to give me your help.

PS: sorry for my english, but i'm french. 👍

**Comment by mchestr** [comment]
Hi, perhaps if you still need custom fonts try looking at the `custom_font.py` added recently, it should hopefully help you out. closing this issue for now, feel free to open a new one if the current code doesn't make sense.
