### ISSUE TITLE
3x16x24 HT1632C with Pi3

### ISSUE THREAD

**Issue by steven-palomino** [mchestr/HT1632C-Python#3]
Hey! 

I realize this project is a bit old but I'm hoping you can help me out. The new matrix panels and Pis seem to be slightly different and I can't seem to get the panel to work. 
The new panel looks like this: 
https://www.dropbox.com/s/k51gqh3oxr7hfrt/1.jpg?dl=0

and Pi looks like this:
https://www.dropbox.com/s/sy505yafshkq9q1/2.jpg?dl=0

I've connected (Pi3 Diagram: https://openclipart.org/image/2400px/svg_to_png/280972/gpiopinsv3withpi.png)
vcc to 5v 
ground to ground 
Data to pin 19 
Write to pin 23
sync to 24 (this is the one i couldn't find clock on matrix for)
cs0 to pin 26

I'd really appreciate any direction as this is driving me crazy :)

**Comment by DizHell** [comment]
Hi,

First sorry for my english i'm french.

Your panel is not a ht1632c, is the old version. Search a code for HT1632 (without 'C')

Good luck

**Comment by steven-palomino** [comment]
I've found several, the problem is they don't go over wiring. Do you have any idea how that can be done?

**Comment by DonKahones** [comment]
Wiring should be the same (Data, Write, and chip select).  I dont see a data pin in your picture of your board....

In addition I believe that there are some differences in the initialization commands that need to be sent to the chip in order for it to work.  See this link for more information 

http://timewitharduino.blogspot.com/2011/10/difference-between-3208-and-0832-led.html

I think that someone needs to change the ht1632c_init function to send the correct initialization commands.   

line 186 of ht1632c.c needs to send the command specific to your display

HT1632_CMD_COMS00 0x20  /* for 8 high NMOS display */
HT1632_CMD_COMS01 0x24  /* for 16 high NMOS diplay  */
HT1632_CMD_COMS10 0x28  /* for 8 high PMOS display */
HT1632_CMD_COMS11 0x2C  /* for 16 high PMOS display */

you'll have to figure out which one applies to your display. My guess is that it is HT1632_CMD_COMS11 that you need to send.  (My old ht1632 sure 0832 used the 8 high PMOS command)

To provide more versatility the display initialization function should probably take some additional arguments to account for the two PMOS. Right now all it does is switch between the two NMOS commands depending on the CHIP_HEIGHT variable.

**Comment by steven-palomino** [comment]
Here's a closer look at the panel: 
https://www.dropbox.com/s/cusr9awn2k79jz1/3.jpg?dl=0

Do you think I need to short J5 in order to access CS?

**Comment by DonKahones** [comment]
hmmm... I cant tell from the picture. if you have a multi meter you can try test continuity to the chip itself.

I tried modifiying the ht1632c.c file like I said and I was able to get some leds to light up.  Its not really doing what its supposed to but its alive. 

I have an old sure0832 with the ht1632 chip so i used HT1632_CMD_COMS10 command.  Try make the change to HT1632_CMD_COMS11 in your ht1632c.c file and see if you get any lights at all.

Remember to recompile (sudo python setup.py install) after you make the change.

**Comment by steven-palomino** [comment]
Okay I'm giving it a try. On a side note, I'm just going off the Raspberry
Pi power. That's still okay right?

**Comment by DonKahones** [comment]
should be for now.  

there are some other changes that need to be made since the ht1632c is meant for multi-color displays.  It looks like some of the examples cycle through some colors.  I'll make a branch for the older ht1632 if I get it to work.

**Comment by steven-palomino** [comment]
also... there's no Clock pin on the matrix, just sync and osc... would sync be clock? or is it not required?

**Comment by steven-palomino** [comment]
changed my init to look like this and still no action :/

```
	// init display
	ht1632c_sendcmd(HT1632_CS_ALL, HT1632_CMD_SYSDIS);
	ht1632c_sendcmd(HT1632_CS_ALL, (CHIP_HEIGHT <= 8) ? HT1632_CMD_COMS11 : HT1632_CMD_COMS11);
	ht1632c_sendcmd(HT1632_CS_ALL, HT1632_CMD_MSTMD);
	ht1632c_sendcmd(HT1632_CS_ALL, HT1632_CMD_RCCLK);
	ht1632c_sendcmd(HT1632_CS_ALL, HT1632_CMD_SYSON);
	ht1632c_sendcmd(HT1632_CS_ALL, HT1632_CMD_LEDON);
	ht1632c_sendcmd(HT1632_CS_ALL, HT1632_CMD_BLOFF);
	ht1632c_sendcmd(HT1632_CS_ALL, HT1632_CMD_PWM);

	ht1632c_clear();
	ht1632c_sendframe();

	return 0;
```

**Comment by DonKahones** [comment]
Got my old SURE0832 working.  created a fork with the settings I had to use.  feel free to check it out and modify what ask any questions if yours still doesnt work.

**Comment by DonKahones** [comment]
I did not use the clock pin.  My pins are:
PI------DISPLAY
CE0(PIN 24) ------CS1 
SCLK(PIN23)------WR
MOSI(PIN19)------DATA
+5V(PIN 2)--------+5V
GND(PIN6)--------GND

**Comment by DonKahones** [comment]
the key to making it all work 1)wiring 2) change init function and 3)editing the panelconfig.h file with the proper settings.

Mine didnt work when recompiling unless I completely deleted the ./build folder whenever making changes

**Comment by steven-palomino** [comment]
hmmm... I've done all that... Do you think this J5 needs to be bridged? 
https://www.dropbox.com/s/cusr9awn2k79jz1/3.jpg?dl=0

It mentions something about that here: 
https://learn.adafruit.com/16x24-led-matrix?view=all#wiring

**Comment by DonKahones** [comment]
hmmm.  yes it does need to be bridged if only using one or two panels.

Also just looked up the panel you have... it looks like it in fact does use the new ht1632c chipset which would mean the original library should work out of the box if you just setup the panelconfig.h file correctly.

try solder that jumper then go back to the original library and just modify the panelconfig.h

**Comment by steven-palomino** [comment]
Ok awesome. So. I have 3 of those panels I want to chain. I wouldn't have
to solder them if I want to use 3 right? Then the question would be where
do I plug the other C's pins? Or how would I connect them?

On Dec 2, 2017 3:43 PM, "DonKahones" <notifications@github.com> wrote:

hmmm. yes it does need to be bridged if only using one or two panels.

Also just looked up the panel you have... it looks like it in fact does use
the new ht1632c chipset which would mean the original library should work
out of the box if you just setup the panelconfig.h file correctly.

try solder that jumper then go back to the original library and just modify
the panelconfig.h

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mchestr/HT1632C-Python/issues/3#issuecomment-348722325>,
or mute the thread

**Comment by DonKahones** [comment]
looks like you wire it up like this 
https://learn.adafruit.com/16x24-led-matrix?view=all#3-10-displays

I dont think the python library supports this configuration thought so you are heading into new territory.

**Comment by steven-palomino** [comment]
Yeah that's what I was afraid of :/
I'll try the bridge with 1 then 2 and see if I can get 3 to work somehow

**Comment by DonKahones** [comment]
thats what I would do.  Start with one panel, make sure it works then tackle the chaining. 

In the panelconfig.h file it talks about chaining the panels with CLK and CS lines but I'm not sure how that would work.

**Comment by steven-palomino** [comment]
Weird. 

I bridged J5. Plugged everything where you listed. built new HT1632C project and ran clock and spiral examples and still nothing. See anything weird here?
https://www.dropbox.com/s/ct6nv46gcah6x0d/4.jpg?dl=0
https://www.dropbox.com/s/1c2ns4lmo45byre/5.jpg?dl=0

**Comment by steven-palomino** [comment]
Just noticed panpelconfig.h comment. Do I just uncomment line 7 about PANEL_24X16 and re-install with setup.py?

**Comment by steven-palomino** [comment]
Modified config to look like this but still nothing :/

```
// ht1632c panel configuration

// Panel's write clock (WR) pin has to be connected to SCLK (14, GPIO 11),
// DATA has to be connected to MOSI (12, GPIO 10).

#define PANEL_32x16C /* preset for bi-color 32x16 panel */
#define PANEL_24x16  /* preset for monochrome 24x16 panel */

// Chained chip select mode.
// Define if chips are chained and connected using CLK/CS lines.
// Don't define if chip select pins are connected directly to output pins.
#define HT1632C_CS_CHAINED
#define HT1632_CLK  10          /* chip select clock pin */
#define HT1632_CS   11

// panel parameters
#define CHIPS_PER_PANEL 6       /* ht1632c chips per panel */
#define PANEL_WIDTH 24          /* panel width (pixels) */
#define PANEL_HEIGHT 16         /* panel height (pixels) */
#define CHIP_WIDTH 8           /* chip width (pixels) */
#define CHIP_HEIGHT 8           /* chip height (pixels) */
#define COLORS 1                /* number of colors (1 or 2) */

#define SPI_FREQ 2560000            /* SPI frequency (Hz; up to 32000000) */
#define CS_CLK_DELAY 10             /* CS pulse length (µs) in chained CS mode */
```

**Comment by DonKahones** [comment]
for a single display i would use the following
```
// ht1632c panel configuration

// Panel's write clock (WR) pin has to be connected to SCLK (14, GPIO 11),
// DATA has to be connected to MOSI (12, GPIO 10).

//#define PANEL_32x16C /* preset for bi-color 32x16 panel */
//#define PANEL_24x16  /* preset for monochrome 24x16 panel */

// Chained chip select mode.
// Define if chips are chained and connected using CLK/CS lines.
// Don't define if chip select pins are connected directly to output pins.
//#define HT1632C_CS_CHAINED
#define HT1632_CLK  10          /* chip select clock pin */
#define HT1632_CS   11

// panel parameters
#define CHIPS_PER_PANEL 1       /* ht1632c chips per panel */
#define PANEL_WIDTH 24          /* panel width (pixels) */
#define PANEL_HEIGHT 16         /* panel height (pixels) */
#define CHIP_WIDTH 24           /* chip width (pixels) */
#define CHIP_HEIGHT 16           /* chip height (pixels) */
#define COLORS 1                /* number of colors (1 or 2) */

#define SPI_FREQ 2560000            /* SPI frequency (Hz; up to 32000000) */
#define CS_CLK_DELAY 10             /* CS pulse length (µs) in chained CS mode */
```

**Comment by DonKahones** [comment]
then delete the ./build folder and recompile

**Comment by steven-palomino** [comment]
so... when I made those changes and deleted build folder I got the following error when I tried to install: 
https://pastebin.com/7gsiGNB4
It also wouldn't run an example.
(I also removed single quotes from your config)

**Comment by DonKahones** [comment]
looks like something got screwed up with the panelconfig.h file and there is a typo somewhere in your version.

**Comment by DonKahones** [comment]
I dont really know how to use github so it keeps doing weird stuff when I was trying to post the code

**Comment by steven-palomino** [comment]
haha well.. I changed the config to look like this and cleared the build folder and still don't get anything. 
Also.. I really appreciate you helping me through this.. I've got no idea why it's not working and there isn't much information out there on this panel with Pi. It's mostly on arduino.
I also get this write error when installing the first time:
https://pastebin.com/xhsjRMJB

Here's the config:

```
// ht1632c panel configuration

// Panel's write clock (WR) pin has to be connected to SCLK (14, GPIO 11),
// DATA has to be connected to MOSI (12, GPIO 10).

//#define PANEL_32x16C /* preset for bi-color 32x16 panel */
//#define PANEL_24x16  /* preset for monochrome 24x16 panel */

// Chained chip select mode.
// Define if chips are chained and connected using CLK/CS lines.
// Don't define if chip select pins are connected directly to output pins.
#define HT1632C_CS_CHAINED
#define HT1632_CLK  10          /* chip select clock pin */
#define HT1632_CS   11

// panel parameters
#define CHIPS_PER_PANEL 1       /* ht1632c chips per panel */
#define PANEL_WIDTH 24          /* panel width (pixels) */
#define PANEL_HEIGHT 16         /* panel height (pixels) */
#define CHIP_WIDTH 24           /* chip width (pixels) */
#define CHIP_HEIGHT 16           /* chip height (pixels) */
#define COLORS 1                /* number of colors (1 or 2) */

#define SPI_FREQ 2560000            /* SPI frequency (Hz; up to 32000000) */
#define CS_CLK_DELAY 10             /* CS pulse length (µs) in chained CS mode */

```

**Comment by DonKahones** [comment]
comment out this line
#define HT1632C_CS_CHAINED

I dont see the write error you are talking about

**Comment by steven-palomino** [comment]
Same thing :(
You have this same panel?

**Comment by DonKahones** [comment]
no,  I dont. I am using an old SURE0832.  I'm  just bored and was able to get mine working so trying to help. 

when you delete the build folder you are doing 

>>sudo rm -r ./build

**Comment by steven-palomino** [comment]
Ah, no. I was doing `sudo rm -r build/` in the actual directory. But I did try that just in case and recompiled with the same result :/
(And still getting that write error on install)

**Comment by DonKahones** [comment]
damn...burn it all down, re-download the original git and start from scratch.  make sure it compiles then delete the build folder and then make the changes to the panelconfig.h

**Comment by steven-palomino** [comment]
Everything seems to compile (even if the error still shows), but the examples still don't run. 
I even tried re-installing WiringPi. Possible I'm missing some other lib or enabling something?

**Comment by DonKahones** [comment]
define "dont run", paste the output

**Comment by steven-palomino** [comment]
When I run an example I get the following

```
pi@raspberrypi:~/Downloads/Another/HT1632C-Python-master/examples $ sudo python spiral.py 
Initializing HT1632C
pi@raspberrypi:~/Downloads/Another/HT1632C-Python-master/examples $ 

```

**Comment by DonKahones** [comment]
thats what you are supposed to see.  
Its means the code is good and either the panelconfig.h is wrong or the wiring is wrong.

try run this test script i made

```
import time

from ht1632cpy import HT1632C

interface = HT1632C(1, 0)
interface.pwm(15)


print('panel width is' + repr(interface.width()) +'.')
print('panel height is' + repr(interface.height()) + '.')

for x in range(0, 32):
  for y in range(0, 32):
    interface.plot(x,y,interface.GREEN)
    print('pixel at x=' + repr(x) + ', y=' + repr(y) + '...')
    interface.sendframe()

interface.clear()
interface.sendframe()
```

**Comment by DonKahones** [comment]
it should print out what the panel height and width settings are then light up every pixel on your panel

**Comment by steven-palomino** [comment]
python script right? put it in ht1632c folder and named it test.py. I get the following: 

```
pi@raspberrypi:~/Downloads/Orig/HT1632C-Python-master/ht1632c $ sudo python test.py 
  File "test.py", line 6
    msg_length = len(msg) * interface.fontwidth(interface.font6x8)
             ^
IndentationError: expected an indented block
```

**Comment by steven-palomino** [comment]
Alright. That edited script worked when I put it in /ht1632c.. it listed out all pixels but nothing lit up :/

**Comment by DonKahones** [comment]
what did it spit out in the terminal

**Comment by DonKahones** [comment]
should be somthing like

>>Initializing HT1632C
>>panel width is32.
>>panel height is8.
>>pixel at x=0, y=0...

**Comment by steven-palomino** [comment]
```
pi@raspberrypi:~/Downloads/Another/HT1632C-Python-master/ht1632c $ sudo python test.py 
Initializing HT1632C
panel width is24.
panel height is16.

```

**Comment by DonKahones** [comment]
if your wiring is right and panelconfig.h is right then that should light up something...

maybe try uncomment
define PANEL_24x16 
in the panelconfig.h

**Comment by DonKahones** [comment]
but that doesnt look like it would do anything... I cant find it referenced anywhere else in the code

**Comment by DonKahones** [comment]
do me a favor a feel the ht1632C chip with your finger when its plugged in. If it burns your finger then it may be bad.

**Comment by steven-palomino** [comment]
No burning thankfully :/

**Comment by DonKahones** [comment]
wired up according to the original git specs or what i provided?

**Comment by steven-palomino** [comment]
Yes. Exactly.
VCC, Ground
then 19, 23, 24
Data, WR, CS1 respectively.. 

There's also cs0 pins on both the pi and the display though

**Comment by DonKahones** [comment]
The CS you want to connect to on the display is CS0

**Comment by DonKahones** [comment]
CE1 (pin 26) on the PI to CS0 on the display

**Comment by steven-palomino** [comment]
OK so CS0 on display to CS0 (pin 24) on Pi? Got that currently and still nothing when I run

**Comment by steven-palomino** [comment]
Ok.. swapped that on the Pi to pin 26 and still nothing

**Comment by DonKahones** [comment]
just for kicks, pull all wires from the display.  wait 30 seconds then rewire, reboot the pi and try running the test script again.  I had one freeze up on me and it wouldnt work until i did that.

**Comment by steven-palomino** [comment]
Will do. I want to think it has something to do with that write error... don't seem like lights would run if there was something wrong with write, right?

**Comment by DonKahones** [comment]
I looked through the pastebin you sent and didnt see any write errors.

**Comment by steven-palomino** [comment]
```
ht1632c/ht1632c.c: In function ‘ht1632c_sendcmd’:
ht1632c/ht1632c.c:128:2: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
  write(ht1632c_spifd, &data, 2);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ht1632c/ht1632c.c: In function ‘ht1632c_sendframe’:
ht1632c/ht1632c.c:242:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   write(ht1632c_spifd, FB_PTR(chip, 0), CHIP_SIZE);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by steven-palomino** [comment]
!!!! It's alive now!

**Comment by DonKahones** [comment]
nice.  reset?

**Comment by steven-palomino** [comment]
Yes. Reset / Rewire.... bizarre. None of the examples work.. but your script does..

**Comment by steven-palomino** [comment]
actually... after I run the examples and try to run your script again it doesn't :/

**Comment by DonKahones** [comment]
the examples have some specific coding that needs to be changed depending on your display characteristics. 

start with only the message.py 

use the one here:

https://github.com/DonKahones/HT1632C-Python/blob/master/examples/message.py

**Comment by DonKahones** [comment]
also you may need to do the reset again for it to come back to life

**Comment by steven-palomino** [comment]
hmm.. could it be RGB data that's causing it to not work? Even message sample kills it

**Comment by DonKahones** [comment]
my version or the main version?

**Comment by DonKahones** [comment]
my version only has the interface.GREEN and interface.BLACK which are 1 and 0 respectively and should work for any single color display

**Comment by steven-palomino** [comment]
Oh sorry didn't realise it was different. I take it the GREEN bit doesn't matter. Even if mine are Red? It's just a ON and OFF at this point?

**Comment by steven-palomino** [comment]
Works, but sends message to only top 3 panels and they're sideways.. and mirrored

**Comment by steven-palomino** [comment]
Is this where the config needs tweaking?

**Comment by DonKahones** [comment]
the ones to change are lines 7 and 15 where you choose what size font to use.

options are from /master/ht1632cpy/interface.py

        self.font3x4num = self.lib.font_3x4_num
        self.font4x5num = self.lib.font_4x5_num
        self.font7x8num = self.lib.font_7x8_num
        self.font4x6 = self.lib.font_4x6
        self.font5x8 = self.lib.font_5x8
        self.font6x8 = self.lib.font_6x8
        self.font7x12 = self.lib.font_7x12
        self.font8x12 = self.lib.font_8x12
        self.font12x16 = self.lib.font_12x16
        self.font4x6sym = self.lib.font_4x6_sym

also when you initialize the interface you can rotate the display with the second parameter.  I think its just 0-3.

**Comment by DonKahones** [comment]
line 21 of message.py 

interface = HT1632C(1, 0)  //default rotation
interface = HT1632C(1, 1) //rotate 90 clockwise
interface = HT1632C(1, 2) //rotate 180
interface = HT1632C(1, 3) // rotate 279 clockwise

**Comment by DonKahones** [comment]
only need to use one of the above options

**Comment by steven-palomino** [comment]
Hmm.. seems to only run on 2 or 3 of the panels and still not in the right way.. not orientation but mirrored.

**Comment by steven-palomino** [comment]
https://www.dropbox.com/s/d3x7jk1oqnd8qut/6.mp4?dl=0

**Comment by DonKahones** [comment]
now that I think about it when I used the adafruit library to drive my display I had the same problem so there may be some inherent differences between the SURE displays and the one you have.  It looks like at a low level they work but you may have to change the character display functions to display properly.

**Comment by DonKahones** [comment]
start by doing a pixel by pixel mapping and see what order they go in.  my test script should have gone from the top left down and then to the right.

**Comment by DonKahones** [comment]
you can probably use the adafruit arduino library as a good base to work off of and copy paste as much as possible

**Comment by steven-palomino** [comment]
Yeah it seems from using the plot() method everything is mapped really weird. 
0,0 is bottom right and 23,15 is top left which makes some sense, but then 7,7 will be the top left of one LED chip and 8,7 (instead of going up one) will be the bottom left pixel on the chip to the left of it. 
The arduino code wasn't very helpful as it didn't seem to have any mappings. How would I begin to do that?

**Comment by DonKahones** [comment]
you might be able to do a coordinate translation if you can figure out which coordinate maps to which pixel.

**Comment by mchestr** [comment]
Did you guys manage to figure it out? TBH I haven't played around with my displays for quite some time, but I do remember they were a bit finicky with the wiring... Looks like you got some help though which is great, hope it all worked out. 

A lot of the library code I gathered from https://github.com/DerBer/ht1632clib I believe, but if yours is an HT1632, you may need to write up your own stuff, perhaps look into the adafruit library for the same display https://github.com/adafruit/HT1632 and see if you can get it working.

Thanks!

**Comment by mchestr** [comment]
closing this issue for now, feel free to open a new issue if something new comes up... but I think the original issue was resolved
